# Site settings
title: Abhinav Pola
author:
  name: Abhinav Pola
  email: abhinavpola7@gmail.com
description: "My blog for cool stuff"

# Build settings
remote_theme: jekyll/minima

# Other configuration settings

header_pages:
  - index.md
  - resume.md # Link to your resume
  - blog.md
  - reading_list.md

